services:  
  go_db:  
    container_name: go_db 
    image: postgres:12  
    environment:  
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME} 
    ports:  
      - "${DB_PORT}:5432"  
    volumes:  
      - pgdata:/var/lib/postgresql/data  

volumes:  
  pgdata: {}